name: linter-check
on: push
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Cloning repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3

            - name: Install dependencies
              uses: make install

            - name: Run lint
              run: make lint
